# Generated by Django 5.0.3 on 2024-03-06 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meuprimeiroapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PessoaBancoDeDados',
            new_name='PessoaBancoDeDado',
        ),
    ]
