# Generated by Django 5.0.3 on 2024-03-07 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meuprimeiroapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViaCepModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.CharField(max_length=20, verbose_name='Cep do Usuário')),
                ('logradouro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Logradouro do Usuário')),
                ('complemento', models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento do Usuário')),
                ('bairro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Localidade do Usuário')),
                ('uf', models.CharField(blank=True, max_length=100, null=True, verbose_name='Estado do Usuário')),
            ],
        ),
    ]
